// Generates a real, indexable page for every tool (e.g. merge-pdf/index.html) from index.html,
// with its own title, description, social preview, structured data and a short how-to + FAQ.
// Also writes sitemap.xml, robots.txt and tool-slugs.js. Run: npm run pages
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(readFileSync(join(root, 'scripts', 'seo-data.json'), 'utf8'));
const template = readFileSync(join(root, 'index.html'), 'utf8');
const { site, tools, commonFaq } = data;

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const json = (obj) => JSON.stringify(obj).replace(/</g, '\\u003c');

function headTags({ url, title, description, image }) {
  return [
    `<link rel="canonical" href="${url}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="${esc(site.name)}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(description)}">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:image" content="${image}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta name="twitter:card" content="summary_large_image">`,
  ].join('\n');
}

function replaceBlock(html, block) {
  const start = html.indexOf('<!-- seo:start -->');
  const end = html.indexOf('<!-- seo:end -->');
  if (start < 0 || end < 0) throw new Error('index.html is missing the seo:start / seo:end block');
  return `${html.slice(0, start)}<!-- seo:start -->\n${block}\n${html.slice(end)}`;
}

function must(html, search, replacement) {
  if (!html.includes(search)) throw new Error(`template is missing: ${search}`);
  return html.replace(search, replacement);
}

for (const t of tools) {
  const url = `${site.url}${t.slug}/`;
  const faq = [...t.faq, ...commonFaq];
  const structured = [
    {
      '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: `${t.name} – ${site.name}`,
      applicationCategory: 'BusinessApplication', operatingSystem: 'Any (web browser), Android',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, description: t.description, url,
    },
    {
      '@context': 'https://schema.org', '@type': 'HowTo', name: `How to use ${t.name}`,
      step: t.steps.map((text, i) => ({ '@type': 'HowToStep', position: i + 1, text })),
    },
    {
      '@context': 'https://schema.org', '@type': 'FAQPage',
      mainEntity: faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })),
    },
  ];
  let html = template;
  html = must(html, '<meta charset="utf-8">', '<meta charset="utf-8">\n<base href="../">');
  html = html.replace(/<title>[\s\S]*?<\/title>/, `<title>${esc(t.title)}</title>`);
  html = html.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${esc(t.description)}">`);
  html = replaceBlock(html, `${headTags({ url, title: t.title, description: t.description, image: `${site.url}og/${t.slug}.png` })}\n<script type="application/ld+json">${json(structured)}</script>`);
  html = must(html, '<body data-view="home">', `<body data-view="tool" data-default-tool="${t.id}">`);
  html = must(html, '<div id="toolSeo" hidden></div>', `<section class="seo-info" id="toolSeo" data-tool="${t.id}">
        <h2>${esc(t.intro)}</h2>
        <h3>How to use ${esc(t.name)}</h3>
        <ol>${t.steps.map((s) => `<li>${esc(s)}</li>`).join('')}</ol>
        <h3>Questions and answers</h3>
        <dl>${faq.map(([q, a]) => `<dt>${esc(q)}</dt><dd>${esc(a)}</dd>`).join('')}</dl>
      </section>`);
  mkdirSync(join(root, t.slug), { recursive: true });
  writeFileSync(join(root, t.slug, 'index.html'), html);
}

// Slugs for the app's links to these pages.
writeFileSync(join(root, 'tool-slugs.js'), `'use strict';\n// Generated by scripts/build-pages.mjs – the indexable page for each tool.\nconst TOOL_SLUGS = ${JSON.stringify(Object.fromEntries(tools.map((t) => [t.id, t.slug])), null, 2)};\n`);

const today = new Date().toISOString().slice(0, 10);
const urls = [site.url, ...tools.map((t) => `${site.url}${t.slug}/`)];
writeFileSync(join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`);
writeFileSync(join(root, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${site.url}sitemap.xml\n`);
console.log(`Wrote ${tools.length} tool pages, sitemap.xml, robots.txt and tool-slugs.js`);
